targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          include_if_null: false
      freezed:
        options:
          union_key: type
          union_value_case: snake